

int _ABVAR_1_t1;
int trigPin=2;  // 发送信号端口
int echoPin =3;  //接收信号端口

int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM()
{
  unsigned long duration=0;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  
  // 产生一个10us的高脉冲去触发TrigPin 
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  
   // 检测脉冲宽度，并计算出距离
  duration = pulseIn(echoPin, HIGH);
   Serial.print(duration);
  duration = duration / 58.3;//  1/58.3=  343/(2*100/1000000)
  return duration;
}


void setup()
{
  Serial.begin(9600);
  
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  
  //digitalWrite(4, LOW);
  _ABVAR_1_t1 = 0;
}

void loop()
{
  _ABVAR_1_t1 = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM() ;
  Serial.print("distance:");
  Serial.print(_ABVAR_1_t1);
  Serial.print("cm");
  Serial.println("");
  delay(1000);
}


